cargo-features = ["edition2024"]

[package]
name = "bin"
version.workspace = true
edition.workspace = true

[dependencies]
sdl2 = { package = "sdl2", version = "0.37.0", features = ["use-pkgconfig"] }
nes = { package = "nes-rs", path = "../nes" }

[package.metadata.vita]
title_id = "RUSTVITA1"
title_name = "NES Emulator"
