cargo-features = ["edition2024"]

[package]
name = "nes-rs"
version.workspace = true
edition.workspace = true

[lib]
name = "nes"

[dependencies]
bitflags = "2.6.0"
rand = "0.8.5"
macros = { path = "../macros" }
